"font: DejaVu Sans Mono for Powerline Book 11 get ir from
"itchyny/lightline.vim github

call plug#begin() 

Plug 'scrooloose/nerdtree'
Plug 'kien/ctrlp.vim'    
Plug 'tmhedberg/simpylfold'
Plug 'pangloss/vim-javascript'
Plug 'crusoexia/vim-javascript-lib'
Plug 'ap/vim-buftabline'     
Plug 'amirh/html-autoclosetag'
Plug 'shutnik/jshint2.vim'   
Plug 'crusoexia/vim-monokai' 
Plug 'KevinGoodsell/vim-csexact'
Plug 'altercation/vim-colors-solarized'
Plug 'mattn/emmet-vim'
Plug 'itchyny/lightline.vim'
Plug 'othree/html5-syntax.vim'
Plug 'craigemery/vim-autotag'
Plug 'majutsushi/tagbar'
Plug 'kh3phr3n/python-syntax'
Plug 'vim-scripts/TagHighlight'
Plug 'davidhalter/jedi-vim'
Plug 'ahayman/vim-nodejs-complete'
Plug 'dkprice/vim-easygrep'
Plug 'samsonw/vim-task' 
Plug 'junegunn/goyo.vim'

call plug#end() 

noremap <Up> <NOP> 
noremap <Down> <NOP> 
noremap <Left> <NOP>
noremap <Right> <NOP>

nnoremap <C-N> :bnext<CR>
nnoremap <C-D> :bd<CR>

nnoremap <C-T> :NERDTreeToggle<CR>

noremap <F9> :exec '!python' shellescape(@%, 1)<cr>

"tasks
noremap <C-A> <ESC>:call Toggle_task_status()<CR>i
noremap <C-A> :call Toggle_task_status()<CR>
"

imap <C-e> <C-y>,

set pastetoggle=<F2>

set hidden
set ls=2 

set number
set relativenumber

set noswapfile
set nobackup
set nowb 
set cursorline

set expandtab
set smarttab

set shiftwidth=4
set tabstop=4

set ai
set si
set wrap

set hlsearch
set incsearch

set foldlevel=1 

set colorcolumn=80

set background=dark
set t_Co=256

syntax enable

colorscheme monokai 

"autocomplete
"set completeopt+=menu,menuone
"set shortmess+=c
"set completeopt+=noinsert
"let g:mucomplete#enable_auto_at_startup = 1

let mapleader=","

let g:jedi#show_call_signatures = "2"

let python_highlight_all = 1

let g:monokai_term_italic = 1

let g:javascript_enable_domhtmlcss = 1

let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component': {
    \   'readonly': '%{&filetype=="help"?"":&readonly?"" :""}',
    \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \ },
    \ 'component_visible_condition': {
    \   'readonly': '(&filetype!="help"&& &readonly)',
    \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))'
    \ },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '', 'right': '' }
    \}

autocmd BufWritePre *.py :UpdateTypesFile
